spring:
  datasource:
    url: jdbc:mysql://localhost:3306/threedays
    username: root
    password: 112900
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      TODO: validate 로 바꾸기
      ddl-auto: create
    database: mysql
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: threedaysapitokensecretkey123149398230